### ISSUE TITLE
`yt` command errors when given a single argument

### ISSUE THREAD

**Issue by antoniouaa** [antoniouaa/spotify_bot#11]
`$yt motherlover` is supposed to play Motherlover by thelonelyisland, link [here](https://www.youtube.com/results?search_query=motherlover)

What it does instead is error out and spits out
```
ERROR: motherlover: YouTube said: Unable to extract video data
Ignoring exception in command yt:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/extractor/youtube.py", line 1910, in _real_extract
    'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: motherlover: YouTube said: Unable to extract video data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/src/music_bot/music_bot/cogs/music.py", line 110, in yt
    await self.playYT(ctx)
  File "/usr/src/music_bot/music_bot/cogs/music.py", line 83, in playYT
    self.playQueue[0], loop=self.bot.loop
  File "/usr/src/music_bot/music_bot/cogs/music.py", line 44, in from_url
    None, lambda: ytdl.extract_info(url, download=not stream)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/music_bot/music_bot/cogs/music.py", line 44, in <lambda>
    None, lambda: ytdl.extract_info(url, download=not stream)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 820, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/lib/python3.6/dist-packages/youtube_dl/YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: motherlover: YouTube said: Unable to extract video data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: DownloadError: ERROR: motherlover: YouTube said: Unable to extract video data
```

**Comment by antoniouaa** [comment]
Fixed with commit 20ec5a5e967d70a72aaf29b860c3b869600ed21c, where `ytsearch` is used instead of a raw search term.
